export default [
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN1",
    control: 0,
    description: "IN1",
    digital_analog: 0,
    filter: 5,
    id: "IN1",
    index: 0,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN2",
    control: 0,
    description: "IN2",
    digital_analog: 0,
    filter: 5,
    id: "IN2",
    index: 1,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN3",
    control: 0,
    description: "IN3",
    digital_analog: 0,
    filter: 5,
    id: "IN3",
    index: 2,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN4",
    control: 0,
    description: "IN4",
    digital_analog: 0,
    filter: 5,
    id: "IN4",
    index: 3,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN5",
    control: 0,
    description: "IN5",
    digital_analog: 0,
    filter: 5,
    id: "IN5",
    index: 4,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN6",
    control: 0,
    description: "IN6",
    digital_analog: 0,
    filter: 5,
    id: "IN6",
    index: 5,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN7",
    control: 0,
    description: "IN7",
    digital_analog: 0,
    filter: 5,
    id: "IN7",
    index: 6,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN8",
    control: 0,
    description: "IN8",
    digital_analog: 0,
    filter: 5,
    id: "IN8",
    index: 7,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN9",
    control: 0,
    description: "IN9",
    digital_analog: 0,
    filter: 5,
    id: "IN9",
    index: 8,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN10",
    control: 0,
    description: "IN10",
    digital_analog: 0,
    filter: 5,
    id: "IN10",
    index: 9,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN11",
    control: 0,
    description: "IN11",
    digital_analog: 0,
    filter: 5,
    id: "IN11",
    index: 10,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN12",
    control: 0,
    description: "IN12",
    digital_analog: 0,
    filter: 5,
    id: "IN12",
    index: 11,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN13",
    control: 0,
    description: "IN13",
    digital_analog: 0,
    filter: 5,
    id: "IN13",
    index: 12,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN14",
    control: 0,
    description: "IN14",
    digital_analog: 0,
    filter: 5,
    id: "IN14",
    index: 13,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN15",
    control: 0,
    description: "IN15",
    digital_analog: 0,
    filter: 5,
    id: "IN15",
    index: 14,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN16",
    control: 0,
    description: "IN16",
    digital_analog: 0,
    filter: 5,
    id: "IN16",
    index: 15,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN17",
    control: 0,
    description: "IN17",
    digital_analog: 0,
    filter: 5,
    id: "IN17",
    index: 16,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN18",
    control: 0,
    description: "IN18",
    digital_analog: 0,
    filter: 5,
    id: "IN18",
    index: 17,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN19",
    control: 0,
    description: "IN19",
    digital_analog: 0,
    filter: 5,
    id: "IN19",
    index: 18,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN20",
    control: 0,
    description: "IN20",
    digital_analog: 0,
    filter: 5,
    id: "IN20",
    index: 19,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN21",
    control: 0,
    description: "IN21",
    digital_analog: 0,
    filter: 5,
    id: "IN21",
    index: 20,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN22",
    control: 0,
    description: "IN22",
    digital_analog: 0,
    filter: 5,
    id: "IN22",
    index: 21,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN23",
    control: 0,
    description: "IN23",
    digital_analog: 0,
    filter: 5,
    id: "IN23",
    index: 22,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN24",
    control: 0,
    description: "IN24",
    digital_analog: 0,
    filter: 5,
    id: "IN24",
    index: 23,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN25",
    control: 0,
    description: "IN25",
    digital_analog: 0,
    filter: 5,
    id: "IN25",
    index: 24,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN26",
    control: 0,
    description: "IN26",
    digital_analog: 0,
    filter: 5,
    id: "IN26",
    index: 25,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN27",
    control: 0,
    description: "IN27",
    digital_analog: 0,
    filter: 5,
    id: "IN27",
    index: 26,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN28",
    control: 0,
    description: "IN28",
    digital_analog: 0,
    filter: 5,
    id: "IN28",
    index: 27,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN29",
    control: 0,
    description: "IN29",
    digital_analog: 0,
    filter: 5,
    id: "IN29",
    index: 28,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN30",
    control: 0,
    description: "IN30",
    digital_analog: 0,
    filter: 5,
    id: "IN30",
    index: 29,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN31",
    control: 0,
    description: "IN31",
    digital_analog: 0,
    filter: 5,
    id: "IN31",
    index: 30,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN32",
    control: 0,
    description: "IN32",
    digital_analog: 0,
    filter: 5,
    id: "IN32",
    index: 31,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN33",
    control: 0,
    description: "IN33",
    digital_analog: 0,
    filter: 5,
    id: "IN33",
    index: 32,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN34",
    control: 0,
    description: "IN34",
    digital_analog: 0,
    filter: 5,
    id: "IN34",
    index: 33,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN35",
    control: 0,
    description: "IN35",
    digital_analog: 0,
    filter: 5,
    id: "IN35",
    index: 34,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN36",
    control: 0,
    description: "IN36",
    digital_analog: 0,
    filter: 5,
    id: "IN36",
    index: 35,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN37",
    control: 0,
    description: "IN37",
    digital_analog: 0,
    filter: 5,
    id: "IN37",
    index: 36,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN38",
    control: 0,
    description: "IN38",
    digital_analog: 0,
    filter: 5,
    id: "IN38",
    index: 37,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN39",
    control: 0,
    description: "IN39",
    digital_analog: 0,
    filter: 5,
    id: "IN39",
    index: 38,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN40",
    control: 0,
    description: "IN40",
    digital_analog: 0,
    filter: 5,
    id: "IN40",
    index: 39,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN41",
    control: 0,
    description: "IN41",
    digital_analog: 0,
    filter: 5,
    id: "IN41",
    index: 40,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN42",
    control: 0,
    description: "IN42",
    digital_analog: 0,
    filter: 5,
    id: "IN42",
    index: 41,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN43",
    control: 0,
    description: "IN43",
    digital_analog: 0,
    filter: 5,
    id: "IN43",
    index: 42,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN44",
    control: 0,
    description: "IN44",
    digital_analog: 0,
    filter: 5,
    id: "IN44",
    index: 43,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN45",
    control: 0,
    description: "IN45",
    digital_analog: 0,
    filter: 5,
    id: "IN45",
    index: 44,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN46",
    control: 0,
    description: "IN46",
    digital_analog: 0,
    filter: 5,
    id: "IN46",
    index: 45,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN47",
    control: 0,
    description: "IN47",
    digital_analog: 0,
    filter: 5,
    id: "IN47",
    index: 46,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN48",
    control: 0,
    description: "IN48",
    digital_analog: 0,
    filter: 5,
    id: "IN48",
    index: 47,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN49",
    control: 0,
    description: "IN49",
    digital_analog: 0,
    filter: 5,
    id: "IN49",
    index: 48,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN50",
    control: 0,
    description: "IN50",
    digital_analog: 0,
    filter: 5,
    id: "IN50",
    index: 49,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN51",
    control: 0,
    description: "IN51",
    digital_analog: 0,
    filter: 5,
    id: "IN51",
    index: 50,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN52",
    control: 0,
    description: "IN52",
    digital_analog: 0,
    filter: 5,
    id: "IN52",
    index: 51,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN53",
    control: 0,
    description: "IN53",
    digital_analog: 0,
    filter: 5,
    id: "IN53",
    index: 52,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN54",
    control: 0,
    description: "IN54",
    digital_analog: 0,
    filter: 5,
    id: "IN54",
    index: 53,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN55",
    control: 0,
    description: "IN55",
    digital_analog: 0,
    filter: 5,
    id: "IN55",
    index: 54,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN56",
    control: 0,
    description: "IN56",
    digital_analog: 0,
    filter: 5,
    id: "IN56",
    index: 55,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN57",
    control: 0,
    description: "IN57",
    digital_analog: 0,
    filter: 5,
    id: "IN57",
    index: 56,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN58",
    control: 0,
    description: "IN58",
    digital_analog: 0,
    filter: 5,
    id: "IN58",
    index: 57,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN59",
    control: 0,
    description: "IN59",
    digital_analog: 0,
    filter: 5,
    id: "IN59",
    index: 58,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN60",
    control: 0,
    description: "IN60",
    digital_analog: 0,
    filter: 5,
    id: "IN60",
    index: 59,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN61",
    control: 0,
    description: "IN61",
    digital_analog: 0,
    filter: 5,
    id: "IN61",
    index: 60,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN62",
    control: 0,
    description: "IN62",
    digital_analog: 0,
    filter: 5,
    id: "IN62",
    index: 61,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN63",
    control: 0,
    description: "IN63",
    digital_analog: 0,
    filter: 5,
    id: "IN63",
    index: 62,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    calibration_h: 0,
    calibration_l: 0,
    calibration_sign: 0,
    command: "1IN64",
    control: 0,
    description: "IN64",
    digital_analog: 0,
    filter: 5,
    id: "IN64",
    index: 63,
    label: "",
    range: 0,
    type: "INPUT",
    unit: 0,
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT1",
    control: 0,
    description: "OUT1",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT1",
    index: 0,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT2",
    control: 0,
    description: "OUT2",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT2",
    index: 1,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT3",
    control: 0,
    description: "OUT3",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT3",
    index: 2,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT4",
    control: 0,
    description: "OUT4",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT4",
    index: 3,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT5",
    control: 0,
    description: "OUT5",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT5",
    index: 4,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT6",
    control: 0,
    description: "OUT6",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT6",
    index: 5,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT7",
    control: 0,
    description: "OUT7",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT7",
    index: 6,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT8",
    control: 0,
    description: "OUT8",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT8",
    index: 7,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT9",
    control: 0,
    description: "OUT9",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT9",
    index: 8,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT10",
    control: 0,
    description: "OUT10",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT10",
    index: 9,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT11",
    control: 0,
    description: "OUT11",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT11",
    index: 10,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT12",
    control: 0,
    description: "OUT12",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT12",
    index: 11,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT13",
    control: 0,
    description: "OUT13",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT13",
    index: 12,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT14",
    control: 0,
    description: "OUT14",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT14",
    index: 13,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT15",
    control: 0,
    description: "OUT15",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT15",
    index: 14,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT16",
    control: 0,
    description: "OUT16",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT16",
    index: 15,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT17",
    control: 0,
    description: "OUT17",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT17",
    index: 16,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT18",
    control: 0,
    description: "OUT18",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT18",
    index: 17,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT19",
    control: 0,
    description: "OUT19",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT19",
    index: 18,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT20",
    control: 0,
    description: "OUT20",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT20",
    index: 19,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT21",
    control: 0,
    description: "OUT21",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT21",
    index: 20,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT22",
    control: 0,
    description: "OUT22",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT22",
    index: 21,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT23",
    control: 0,
    description: "OUT23",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT23",
    index: 22,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT24",
    control: 0,
    description: "OUT24",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT24",
    index: 23,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT25",
    control: 0,
    description: "OUT25",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT25",
    index: 24,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT26",
    control: 0,
    description: "OUT26",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT26",
    index: 25,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT27",
    control: 0,
    description: "OUT27",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT27",
    index: 26,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT28",
    control: 0,
    description: "OUT28",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT28",
    index: 27,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT29",
    control: 0,
    description: "OUT29",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT29",
    index: 28,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT30",
    control: 0,
    description: "OUT30",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT30",
    index: 29,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT31",
    control: 0,
    description: "OUT31",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT31",
    index: 30,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT32",
    control: 0,
    description: "OUT32",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT32",
    index: 31,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT33",
    control: 0,
    description: "OUT33",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT33",
    index: 32,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT34",
    control: 0,
    description: "OUT34",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT34",
    index: 33,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT35",
    control: 0,
    description: "OUT35",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT35",
    index: 34,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT36",
    control: 0,
    description: "OUT36",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT36",
    index: 35,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT37",
    control: 0,
    description: "OUT37",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT37",
    index: 36,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT38",
    control: 0,
    description: "OUT38",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT38",
    index: 37,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT39",
    control: 0,
    description: "OUT39",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT39",
    index: 38,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT40",
    control: 0,
    description: "OUT40",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT40",
    index: 39,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT41",
    control: 0,
    description: "OUT41",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT41",
    index: 40,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT42",
    control: 0,
    description: "OUT42",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT42",
    index: 41,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT43",
    control: 0,
    description: "OUT43",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT43",
    index: 42,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT44",
    control: 0,
    description: "OUT44",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT44",
    index: 43,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT45",
    control: 0,
    description: "OUT45",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT45",
    index: 44,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT46",
    control: 0,
    description: "OUT46",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT46",
    index: 45,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT47",
    control: 0,
    description: "OUT47",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT47",
    index: 46,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT48",
    control: 0,
    description: "OUT48",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT48",
    index: 47,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT49",
    control: 0,
    description: "OUT49",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT49",
    index: 48,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT50",
    control: 0,
    description: "OUT50",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT50",
    index: 49,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT51",
    control: 0,
    description: "OUT51",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT51",
    index: 50,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT52",
    control: 0,
    description: "OUT52",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT52",
    index: 51,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT53",
    control: 0,
    description: "OUT53",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT53",
    index: 52,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT54",
    control: 0,
    description: "OUT54",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT54",
    index: 53,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT55",
    control: 0,
    description: "OUT55",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT55",
    index: 54,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT56",
    control: 0,
    description: "OUT56",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT56",
    index: 55,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT57",
    control: 0,
    description: "OUT57",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT57",
    index: 56,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT58",
    control: 0,
    description: "OUT58",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT58",
    index: 57,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT59",
    control: 0,
    description: "OUT59",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT59",
    index: 58,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT60",
    control: 0,
    description: "OUT60",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT60",
    index: 59,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT61",
    control: 0,
    description: "OUT61",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT61",
    index: 60,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT62",
    control: 0,
    description: "OUT62",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT62",
    index: 61,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT63",
    control: 0,
    description: "OUT63",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT63",
    index: 62,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1OUT64",
    control: 0,
    description: "OUT64",
    digital_analog: 0,
    high_voltage: 0,
    hw_switch_status: 1,
    id: "OUT64",
    index: 63,
    label: "",
    low_voltage: 0,
    range: 0,
    type: "OUTPUT",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR1",
    control: 0,
    description: "VAR1",
    digital_analog: 0,
    id: "VAR1",
    index: 0,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 70000,
  },
  {
    auto_manual: 0,
    command: "1VAR2",
    control: 0,
    description: "VAR2",
    digital_analog: 0,
    id: "VAR2",
    index: 1,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR3",
    control: 0,
    description: "VAR3",
    digital_analog: 0,
    id: "VAR3",
    index: 2,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR4",
    control: 0,
    description: "VAR4",
    digital_analog: 0,
    id: "VAR4",
    index: 3,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR5",
    control: 0,
    description: "VAR5",
    digital_analog: 0,
    id: "VAR5",
    index: 4,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR6",
    control: 0,
    description: "VAR6",
    digital_analog: 0,
    id: "VAR6",
    index: 5,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR7",
    control: 0,
    description: "VAR7",
    digital_analog: 0,
    id: "VAR7",
    index: 6,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR8",
    control: 0,
    description: "VAR8",
    digital_analog: 0,
    id: "VAR8",
    index: 7,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR9",
    control: 0,
    description: "VAR9",
    digital_analog: 0,
    id: "VAR9",
    index: 8,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR10",
    control: 0,
    description: "VAR10",
    digital_analog: 0,
    id: "VAR10",
    index: 9,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR11",
    control: 0,
    description: "VAR11",
    digital_analog: 0,
    id: "VAR11",
    index: 10,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR12",
    control: 0,
    description: "VAR12",
    digital_analog: 0,
    id: "VAR12",
    index: 11,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR13",
    control: 0,
    description: "VAR13",
    digital_analog: 0,
    id: "VAR13",
    index: 12,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR14",
    control: 0,
    description: "VAR14",
    digital_analog: 0,
    id: "VAR14",
    index: 13,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR15",
    control: 0,
    description: "VAR15",
    digital_analog: 0,
    id: "VAR15",
    index: 14,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR16",
    control: 0,
    description: "VAR16",
    digital_analog: 0,
    id: "VAR16",
    index: 15,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR17",
    control: 0,
    description: "VAR17",
    digital_analog: 0,
    id: "VAR17",
    index: 16,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR18",
    control: 0,
    description: "VAR18",
    digital_analog: 0,
    id: "VAR18",
    index: 17,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR19",
    control: 0,
    description: "VAR19",
    digital_analog: 0,
    id: "VAR19",
    index: 18,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR20",
    control: 0,
    description: "VAR20",
    digital_analog: 0,
    id: "VAR20",
    index: 19,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR21",
    control: 0,
    description: "VAR21",
    digital_analog: 0,
    id: "VAR21",
    index: 20,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR22",
    control: 0,
    description: "VAR22",
    digital_analog: 0,
    id: "VAR22",
    index: 21,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR23",
    control: 0,
    description: "VAR23",
    digital_analog: 0,
    id: "VAR23",
    index: 22,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR24",
    control: 0,
    description: "VAR24",
    digital_analog: 0,
    id: "VAR24",
    index: 23,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR25",
    control: 0,
    description: "VAR25",
    digital_analog: 0,
    id: "VAR25",
    index: 24,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR26",
    control: 0,
    description: "VAR26",
    digital_analog: 0,
    id: "VAR26",
    index: 25,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR27",
    control: 0,
    description: "VAR27",
    digital_analog: 0,
    id: "VAR27",
    index: 26,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR28",
    control: 0,
    description: "VAR28",
    digital_analog: 0,
    id: "VAR28",
    index: 27,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR29",
    control: 0,
    description: "VAR29",
    digital_analog: 0,
    id: "VAR29",
    index: 28,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR30",
    control: 0,
    description: "VAR30",
    digital_analog: 0,
    id: "VAR30",
    index: 29,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR31",
    control: 0,
    description: "VAR31",
    digital_analog: 0,
    id: "VAR31",
    index: 30,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR32",
    control: 0,
    description: "VAR32",
    digital_analog: 0,
    id: "VAR32",
    index: 31,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR33",
    control: 0,
    description: "VAR33",
    digital_analog: 0,
    id: "VAR33",
    index: 32,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR34",
    control: 0,
    description: "VAR34",
    digital_analog: 0,
    id: "VAR34",
    index: 33,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR35",
    control: 0,
    description: "VAR35",
    digital_analog: 0,
    id: "VAR35",
    index: 34,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR36",
    control: 0,
    description: "VAR36",
    digital_analog: 0,
    id: "VAR36",
    index: 35,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR37",
    control: 0,
    description: "VAR37",
    digital_analog: 0,
    id: "VAR37",
    index: 36,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR38",
    control: 0,
    description: "VAR38",
    digital_analog: 0,
    id: "VAR38",
    index: 37,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR39",
    control: 0,
    description: "VAR39",
    digital_analog: 0,
    id: "VAR39",
    index: 38,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR40",
    control: 0,
    description: "VAR40",
    digital_analog: 0,
    id: "VAR40",
    index: 39,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR41",
    control: 0,
    description: "VAR41",
    digital_analog: 0,
    id: "VAR41",
    index: 40,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR42",
    control: 0,
    description: "VAR42",
    digital_analog: 0,
    id: "VAR42",
    index: 41,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR43",
    control: 0,
    description: "VAR43",
    digital_analog: 0,
    id: "VAR43",
    index: 42,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR44",
    control: 0,
    description: "VAR44",
    digital_analog: 0,
    id: "VAR44",
    index: 43,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR45",
    control: 0,
    description: "VAR45",
    digital_analog: 0,
    id: "VAR45",
    index: 44,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR46",
    control: 0,
    description: "VAR46",
    digital_analog: 0,
    id: "VAR46",
    index: 45,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR47",
    control: 0,
    description: "VAR47",
    digital_analog: 0,
    id: "VAR47",
    index: 46,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR48",
    control: 0,
    description: "VAR48",
    digital_analog: 0,
    id: "VAR48",
    index: 47,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR49",
    control: 0,
    description: "VAR49",
    digital_analog: 0,
    id: "VAR49",
    index: 48,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR50",
    control: 0,
    description: "VAR50",
    digital_analog: 0,
    id: "VAR50",
    index: 49,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR51",
    control: 0,
    description: "VAR51",
    digital_analog: 0,
    id: "VAR51",
    index: 50,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR52",
    control: 0,
    description: "VAR52",
    digital_analog: 0,
    id: "VAR52",
    index: 51,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR53",
    control: 0,
    description: "VAR53",
    digital_analog: 0,
    id: "VAR53",
    index: 52,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR54",
    control: 0,
    description: "VAR54",
    digital_analog: 0,
    id: "VAR54",
    index: 53,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR55",
    control: 0,
    description: "VAR55",
    digital_analog: 0,
    id: "VAR55",
    index: 54,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR56",
    control: 0,
    description: "VAR56",
    digital_analog: 0,
    id: "VAR56",
    index: 55,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR57",
    control: 0,
    description: "VAR57",
    digital_analog: 0,
    id: "VAR57",
    index: 56,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR58",
    control: 0,
    description: "VAR58",
    digital_analog: 0,
    id: "VAR58",
    index: 57,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR59",
    control: 0,
    description: "VAR59",
    digital_analog: 0,
    id: "VAR59",
    index: 58,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR60",
    control: 0,
    description: "VAR60",
    digital_analog: 0,
    id: "VAR60",
    index: 59,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR61",
    control: 0,
    description: "VAR61",
    digital_analog: 0,
    id: "VAR61",
    index: 60,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR62",
    control: 0,
    description: "VAR62",
    digital_analog: 0,
    id: "VAR62",
    index: 61,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR63",
    control: 0,
    description: "VAR63",
    digital_analog: 0,
    id: "VAR63",
    index: 62,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR64",
    control: 0,
    description: "VAR64",
    digital_analog: 0,
    id: "VAR64",
    index: 63,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR65",
    control: 0,
    description: "VAR65",
    digital_analog: 0,
    id: "VAR65",
    index: 64,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR66",
    control: 0,
    description: "VAR66",
    digital_analog: 0,
    id: "VAR66",
    index: 65,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR67",
    control: 0,
    description: "VAR67",
    digital_analog: 0,
    id: "VAR67",
    index: 66,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR68",
    control: 0,
    description: "VAR68",
    digital_analog: 0,
    id: "VAR68",
    index: 67,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR69",
    control: 0,
    description: "VAR69",
    digital_analog: 0,
    id: "VAR69",
    index: 68,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR70",
    control: 0,
    description: "VAR70",
    digital_analog: 0,
    id: "VAR70",
    index: 69,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR71",
    control: 0,
    description: "VAR71",
    digital_analog: 0,
    id: "VAR71",
    index: 70,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR72",
    control: 0,
    description: "VAR72",
    digital_analog: 0,
    id: "VAR72",
    index: 71,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR73",
    control: 0,
    description: "VAR73",
    digital_analog: 0,
    id: "VAR73",
    index: 72,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR74",
    control: 0,
    description: "VAR74",
    digital_analog: 0,
    id: "VAR74",
    index: 73,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR75",
    control: 0,
    description: "VAR75",
    digital_analog: 0,
    id: "VAR75",
    index: 74,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR76",
    control: 0,
    description: "VAR76",
    digital_analog: 0,
    id: "VAR76",
    index: 75,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR77",
    control: 0,
    description: "VAR77",
    digital_analog: 0,
    id: "VAR77",
    index: 76,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR78",
    control: 0,
    description: "VAR78",
    digital_analog: 0,
    id: "VAR78",
    index: 77,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR79",
    control: 0,
    description: "VAR79",
    digital_analog: 0,
    id: "VAR79",
    index: 78,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR80",
    control: 0,
    description: "VAR80",
    digital_analog: 0,
    id: "VAR80",
    index: 79,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR81",
    control: 0,
    description: "VAR81",
    digital_analog: 0,
    id: "VAR81",
    index: 80,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR82",
    control: 0,
    description: "VAR82",
    digital_analog: 0,
    id: "VAR82",
    index: 81,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR83",
    control: 0,
    description: "VAR83",
    digital_analog: 0,
    id: "VAR83",
    index: 82,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR84",
    control: 0,
    description: "VAR84",
    digital_analog: 0,
    id: "VAR84",
    index: 83,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR85",
    control: 0,
    description: "VAR85",
    digital_analog: 0,
    id: "VAR85",
    index: 84,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR86",
    control: 0,
    description: "VAR86",
    digital_analog: 0,
    id: "VAR86",
    index: 85,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR87",
    control: 0,
    description: "VAR87",
    digital_analog: 0,
    id: "VAR87",
    index: 86,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR88",
    control: 0,
    description: "VAR88",
    digital_analog: 0,
    id: "VAR88",
    index: 87,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR89",
    control: 0,
    description: "VAR89",
    digital_analog: 0,
    id: "VAR89",
    index: 88,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR90",
    control: 0,
    description: "VAR90",
    digital_analog: 0,
    id: "VAR90",
    index: 89,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR91",
    control: 0,
    description: "VAR91",
    digital_analog: 0,
    id: "VAR91",
    index: 90,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR92",
    control: 0,
    description: "VAR92",
    digital_analog: 0,
    id: "VAR92",
    index: 91,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR93",
    control: 0,
    description: "VAR93",
    digital_analog: 0,
    id: "VAR93",
    index: 92,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR94",
    control: 0,
    description: "VAR94",
    digital_analog: 0,
    id: "VAR94",
    index: 93,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR95",
    control: 0,
    description: "VAR95",
    digital_analog: 0,
    id: "VAR95",
    index: 94,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR96",
    control: 0,
    description: "VAR96",
    digital_analog: 0,
    id: "VAR96",
    index: 95,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR97",
    control: 0,
    description: "VAR97",
    digital_analog: 0,
    id: "VAR97",
    index: 96,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR98",
    control: 0,
    description: "VAR98",
    digital_analog: 0,
    id: "VAR98",
    index: 97,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR99",
    control: 0,
    description: "VAR99",
    digital_analog: 0,
    id: "VAR99",
    index: 98,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR100",
    control: 0,
    description: "VAR100",
    digital_analog: 0,
    id: "VAR100",
    index: 99,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR101",
    control: 0,
    description: "VAR101",
    digital_analog: 0,
    id: "VAR101",
    index: 100,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR102",
    control: 0,
    description: "VAR102",
    digital_analog: 0,
    id: "VAR102",
    index: 101,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR103",
    control: 0,
    description: "VAR103",
    digital_analog: 0,
    id: "VAR103",
    index: 102,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR104",
    control: 0,
    description: "VAR104",
    digital_analog: 0,
    id: "VAR104",
    index: 103,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR105",
    control: 0,
    description: "VAR105",
    digital_analog: 0,
    id: "VAR105",
    index: 104,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR106",
    control: 0,
    description: "VAR106",
    digital_analog: 0,
    id: "VAR106",
    index: 105,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR107",
    control: 0,
    description: "VAR107",
    digital_analog: 0,
    id: "VAR107",
    index: 106,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR108",
    control: 0,
    description: "VAR108",
    digital_analog: 0,
    id: "VAR108",
    index: 107,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR109",
    control: 0,
    description: "VAR109",
    digital_analog: 0,
    id: "VAR109",
    index: 108,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR110",
    control: 0,
    description: "VAR110",
    digital_analog: 0,
    id: "VAR110",
    index: 109,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR111",
    control: 0,
    description: "VAR111",
    digital_analog: 0,
    id: "VAR111",
    index: 110,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR112",
    control: 0,
    description: "VAR112",
    digital_analog: 0,
    id: "VAR112",
    index: 111,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR113",
    control: 0,
    description: "VAR113",
    digital_analog: 0,
    id: "VAR113",
    index: 112,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR114",
    control: 0,
    description: "VAR114",
    digital_analog: 0,
    id: "VAR114",
    index: 113,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR115",
    control: 0,
    description: "VAR115",
    digital_analog: 0,
    id: "VAR115",
    index: 114,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR116",
    control: 0,
    description: "VAR116",
    digital_analog: 0,
    id: "VAR116",
    index: 115,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR117",
    control: 0,
    description: "VAR117",
    digital_analog: 0,
    id: "VAR117",
    index: 116,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR118",
    control: 0,
    description: "VAR118",
    digital_analog: 0,
    id: "VAR118",
    index: 117,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR119",
    control: 0,
    description: "VAR119",
    digital_analog: 0,
    id: "VAR119",
    index: 118,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR120",
    control: 0,
    description: "VAR120",
    digital_analog: 0,
    id: "VAR120",
    index: 119,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR121",
    control: 0,
    description: "VAR121",
    digital_analog: 0,
    id: "VAR121",
    index: 120,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR122",
    control: 0,
    description: "VAR122",
    digital_analog: 0,
    id: "VAR122",
    index: 121,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR123",
    control: 0,
    description: "VAR123",
    digital_analog: 0,
    id: "VAR123",
    index: 122,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR124",
    control: 0,
    description: "VAR124",
    digital_analog: 0,
    id: "VAR124",
    index: 123,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR125",
    control: 0,
    description: "VAR125",
    digital_analog: 0,
    id: "VAR125",
    index: 124,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR126",
    control: 0,
    description: "VAR126",
    digital_analog: 0,
    id: "VAR126",
    index: 125,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR127",
    control: 0,
    description: "VAR127",
    digital_analog: 0,
    id: "VAR127",
    index: 126,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1VAR128",
    control: 0,
    description: "VAR128",
    digital_analog: 0,
    id: "VAR128",
    index: 127,
    label: "",
    range: 0,
    type: "VARIABLE",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1PRG1",
    description: "PRG1",
    id: "PRG1",
    index: 0,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG2",
    description: "PRG2",
    id: "PRG2",
    index: 1,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG3",
    description: "PRG3",
    id: "PRG3",
    index: 2,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG4",
    description: "PRG4",
    id: "PRG4",
    index: 3,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG5",
    description: "PRG5",
    id: "PRG5",
    index: 4,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG6",
    description: "PRG6",
    id: "PRG6",
    index: 5,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG7",
    description: "PRG7",
    id: "PRG7",
    index: 6,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG8",
    description: "PRG8",
    id: "PRG8",
    index: 7,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG9",
    description: "PRG9",
    id: "PRG9",
    index: 8,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG10",
    description: "PRG10",
    id: "PRG10",
    index: 9,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG11",
    description: "PRG11",
    id: "PRG11",
    index: 10,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG12",
    description: "PRG12",
    id: "PRG12",
    index: 11,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG13",
    description: "PRG13",
    id: "PRG13",
    index: 12,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG14",
    description: "PRG14",
    id: "PRG14",
    index: 13,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG15",
    description: "PRG15",
    id: "PRG15",
    index: 14,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1PRG16",
    description: "PRG16",
    id: "PRG16",
    index: 15,
    label: "",
    status: 0,
    type: "PROGRAM",
  },
  {
    auto_manual: 0,
    command: "1SCH1",
    description: "",
    id: "SCH1",
    index: 0,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH2",
    description: "",
    id: "SCH2",
    index: 1,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH3",
    description: "",
    id: "SCH3",
    index: 2,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH4",
    description: "",
    id: "SCH4",
    index: 3,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH5",
    description: "",
    id: "SCH5",
    index: 4,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH6",
    description: "",
    id: "SCH6",
    index: 5,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH7",
    description: "",
    id: "SCH7",
    index: 6,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1SCH8",
    description: "",
    id: "SCH8",
    index: 7,
    label: "",
    output: 0,
    state1: 0,
    state2: 0,
    type: "SCHEDULE",
  },
  {
    auto_manual: 0,
    command: "1CAL1",
    description: "",
    id: "CAL1",
    index: 0,
    label: "",
    type: "HOLIDAY",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1CAL2",
    description: "",
    id: "CAL2",
    index: 1,
    label: "",
    type: "HOLIDAY",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1CAL3",
    description: "",
    id: "CAL3",
    index: 2,
    label: "",
    type: "HOLIDAY",
    value: 0,
  },
  {
    auto_manual: 0,
    command: "1CAL4",
    description: "",
    id: "CAL4",
    index: 3,
    label: "",
    type: "HOLIDAY",
    value: 0,
  },
];
