// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::{Queryable, Selectable};
use serde::Serialize;

use crate::schema::modbus_register_items;


#[derive(Queryable, Selectable, Serialize, Debug)]
#[diesel(table_name = modbus_register_items)]
pub struct ModbusRegisterItem {
    pub id: i32,
    pub register_address: i32,
    pub operation: Option<String>,
    pub register_length: i32,
    pub register_name: Option<String>,
    pub data_format: String,
    pub description: Option<String>,
    pub device_name: String,
    pub status: String,
    pub unit: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

