//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub mime_type: String,
    pub path: String,
    pub status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::modbus_register_devices::Entity")]
    ModbusRegisterDevices,
}

impl Related<super::modbus_register_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModbusRegisterDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
