//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.3

pub mod prelude;

pub mod files;
pub mod modbus_register;
pub mod modbus_register_devices;
pub mod modbus_register_product_device_mapping;
pub mod modbus_register_settings;
pub mod user;

// ============================================================================
// DATABASE MANAGEMENT ENTITIES - New comprehensive database management system
// ============================================================================

pub mod application_settings;
pub mod database_partitions;

// ============================================================================
// ABSTRACTED ENTITIES - T3000 device database entities (used by T3000 modules)
// ============================================================================

pub mod t3_device;
