//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "modbus_register_devices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    pub description: Option<String>,
    pub status: String,
    pub private: Option<bool>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::modbus_register::Entity")]
    ModbusRegister,
    #[sea_orm(has_many = "super::modbus_register_device_name_id_mapping::Entity")]
    ModbusRegisterDeviceNameIdMapping,
}

impl Related<super::modbus_register::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModbusRegister.def()
    }
}

impl Related<super::modbus_register_device_name_id_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModbusRegisterDeviceNameIdMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
