//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "modbus_register_product_device_mapping")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_id: i32,
    pub device_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::modbus_register_devices::Entity",
        from = "Column::DeviceId",
        to = "super::modbus_register_devices::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ModbusRegisterDevices,
}

impl Related<super::modbus_register_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModbusRegisterDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
