//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::modbus_register::Entity as ModbusRegister;
pub use super::modbus_register_settings::Entity as ModbusRegisterSettings;
pub use super::user::Entity as User;
