//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.3

pub use super::modbus_register::Entity as ModbusRegister;
pub use super::modbus_register_device_name_id_mapping::Entity as ModbusRegisterDeviceNameIdMapping;
pub use super::modbus_register_devices::Entity as ModbusRegisterDevices;
pub use super::modbus_register_settings::Entity as ModbusRegisterSettings;
pub use super::user::Entity as User;
